export const SET_CLIENT_PROPOSAL_DATA = 'SET_CLIENT_PROPOSAL_DATA';
export const SET_CLIENT_SHOWING = 'SET_CLIENT_SHOWING';
export const SET_ALL_CLIENTS = 'SET_ALL_CLIENTS';
export const SET_CLIENT_STATUS = 'SET_CLIENT_STATUS';
export const SET_PROPOSAL_AS_COMPLETE = 'SET_PROPOSAL_AS_COMPLETE';

export const INCREASE_REQUIREMENT_ATTEMPTS = 'INCREASE_REQUIREMENT_ATTEMPTS';
export const SET_REQUIREMENT_CORRECTNESS = 'SET_REQUIREMENT_CORRECTNESS';
export const RESET_REQUIREMENT_ATTEMPTS = 'RESET_REQUIREMENT_ATTEMPTS';
export const SET_REQUIREMENT_FEEDBACK = 'SET_REQUIREMENT_FEEDBACK';
export const DISPLAY_REQUIREMENT_FEEDBACK = 'DISPLAY_REQUIREMENT_FEEDBACK';
export const HIDE_REQUIREMENT_FEEDBACK = 'HIDE_REQUIREMENT_FEEDBACK';

export const SET_CLIENT_LOCKED = 'SET_CLIENT_LOCKED';
export const UNLOCK_CLIENT = 'UNLOCK_CLIENT';

export const DISPLAY_SOLUTION_FEEDBACK = 'DISPLAY_SOLUTION_FEEDBACK';
export const HIDE_SOLUTION_FEEDBACK = 'HIDE_SOLUTION_FEEDBACK';
export const SET_SOLUTION_FEEDBACK = 'SET_SOLUTION_FEEDBACK';
export const SET_SOLUTION_CORRECTNESS = 'SET_SOLUTION_CORRECTNESS';
export const INCREASE_SOLUTION_ATTEMPTS = 'INCREASE_SOLUTION_ATTEMPTS';
export const SET_SOLUTION_HAS_GIVEN_UP = 'SET_SOLUTION_HAS_GIVEN_UP';
export const SET_SOLUTION_SCORE = 'SET_SOLUTION_SCORE';
