export const SET_DIAGNOSTIC_COMPLETION = 'SET_DIAGNOSTIC_COMPLETION';
export const SET_DIAGNOSTIC_VISITED = 'SET_DIAGNOSTIC_VISITED';
export const SET_REGION = 'SET_REGION';
export const RESET_DIAGNOSTIC = 'RESET_DIAGNOSTIC';
export const SET_DIAGNOSTIC_DATA = 'SET_DIAGNOSTIC_DATA';
