export const SET_CHALLENGES = 'SET_CHALLENGES';
export const SET_FAMILIES = 'SET_FAMILIES';
export const MAP_STATE_INITIALISED = 'MAP_STATE_INITIALISED';

export const UPDATE_CHALLENGE_STATUS = 'UPDATE_CHALLENGE_STATUS';
export const UPDATE_FAMILY_STATUS = 'UPDATE_FAMILY_STATUS';

export const SET_LAST_CHALLENGES_MODIFIED = 'SET_LAST_CHALLENGES_MODIFIED';
export const SET_LAST_PRODUCT_COMPLETED = 'SET_LAST_PRODUCT_COMPLETED';
export const RESET_LAST_PRODUCT_COMPLETED = 'RESET_LAST_PRODUCT_COMPLETED';

export const SET_CURRENT_FAMILY_PRODUCT = 'SET_CURRENT_FAMILY_PRODUCT';

export const ADD_PERFECT_CHALLENGE = 'ADD_PERFECT_CHALLENGE';
export const SET_COMPLETED_PRODUCTS = 'SET_COMPLETED_PRODUCTS';
export const ADD_COMPLETED_PRODUCT = 'ADD_COMPLETED_PRODUCT';
export const SET_COMPLETED_CHALLENGES = 'SET_COMPLETED_CHALLENGES';
export const ADD_COMPLETED_CHALLENGE = 'ADD_COMPLETED_CHALLENGE';

export const RESET_PROGRESS = 'RESET_PROGRESS';

export const SET_PRODUCT_PAGE_VIEWED_SESSION = 'SET_PRODUCT_PAGE_VIEWED_SESSION';
