
export const SET_TOTAL_SCORE = 'SET_TOTAL_SCORE';
export const SET_DISPLAYED_SCORE = 'SET_DISPLAYED_SCORE';
export const UPDATE_DISPLAYED_SCORE = 'UPDATE_DISPLAYED_SCORE';
export const SET_RUNNING_SCORE = 'SET_RUNNING_SCORE';
export const SET_RANK = 'SET_RANK';
export const SET_SCORES = 'SET_SCORES';
export const INCREASE_SCORE = 'INCREASE_SCORE';
export const DECREASE_SCORE = 'DECREASE_SCORE';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const INCREASE_CHALLENGES_COMPLETED = 'INCREASE_CHALLENGES_COMPLETED';
export const INCREASE_PERFECT_BONUS = 'INCREASE_PERFECT_BONUS';
export const INCREASE_STREAK_BONUS = 'INCREASE_STREAK_BONUS';
export const INCREASE_PRODUCTS_COMPLETED = 'INCREASE_PRODUCTS_COMPLETED';
export const INCREASE_CLIENT_NEEDS = 'INCREASE_CLIENT_NEEDS';
export const INCREASE_PROPOSALS_COMPLETED = 'INCREASE_PROPOSALS_COMPLETED';
export const INCREASE_ACHIEVEMENTS_UNLOCKED = 'INCREASE_ACHIEVEMENTS_UNLOCKED';

export const RESET_RUNNING_CATEGORIES = 'RESET_RUNNING_CATEGORIES';
export const RESET_ALL_SCORES = 'RESET_ALL_SCORES';
