export const INITIALISE_SCORM = 'INITIALISE_SCORM';

export const SET_LESSON_LOCATION = 'SET_LESSON_LOCATION';
export const SET_COMPLETION_STATUS = 'SET_COMPLETION_STATUS';
export const SET_SUSPEND_DATA_ITEM = 'GET_SUSPEND_DATA_ITEM';
export const SET_SCORM_VALUE = 'SET_SCORM_VALUE';

export const COMMIT = 'COMMIT';
export const TERMINATE_SCORM = 'TERMINATE_SCORM';

export const PREPARE_SUSPEND_DATA = 'PREPARE_SUSPEND_DATA';
