export const INCREASE_STREAK = 'INCREASE_STREAK';
export const SET_STREAK = 'SET_STREAK';
export const RESET_STREAK_PROGRESS = 'RESET_STREAK_PROGRESS';
export const CHECK_STREAK_STATUS = 'CHECK_STREAK_STATUS';
