/**
 * Static scores
 */

export const CHALLENGE_NOT_STARTED = 0;
export const CHALLENGE_COMPLETED = 10000;
export const PERFECT_CHALLENGE = 5000;
export const BONUS_STREAK_COMPLETED = 20000;
export const PRODUCT_COMPLETED = 50000;

export const CHALLENGE_COMPLETED_PERFECT = CHALLENGE_COMPLETED + PERFECT_CHALLENGE;
